apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t8to
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t8to
    app.kubernetes.io/part-of: tkrw-pr714-0075-0034-app
  name: devfile-sample-t8to
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t8to
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t8to
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0034-tenant/tkrw-pr714-0075-0034-app/devfile-sample-t8to@sha256:a4a9914d1233c05a54f1778be0af16c888f16e1d608368c4f81f378c6db215b5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
